klutchell/balena-pihole

pihole/Dockerfile
Signed-off-by: Chris Crocker-White <chriscw@balena.io>
=> Pin to Debian stretch fixes #12

README.md, pihole/services/padd/run
https://github.com/klutchell/balena-pihole/issues/50
sleep before starting padd to avoid race condition on ftl port
=> delay padd run

pihole/Dockerfile
- [pihole/pihole:v5.3.4](https://hub.docker.com/layers/pihole/pihole/v5.3.4/images/sha256-73b0aaeaaed89d67e2be8939697c477a834bdf42b5a02fed99107579c9d2fdfa?context=explore)
- [pi-hole/PADD v3.5](https://github.com/pi-hole/PADD/commit/649d67c375d20efb683cba53845983535151977a)
=> Update FTL to v5.3.4 and PADD to v3.5

pihole/Dockerfile
* [pihole/PADD v3.5.1](https://github.com/pi-hole/PADD/commit/ef5acdc7e09389ce4212726d43f084c25a82b53a#diff-42c44861235d0baff7c03aea0fe6c7b7cb95f444c3a398c6d96da1290fc6bc01)
=> Update PADD to v3.5.1

README.md, balena.yml
Signed-off-by: Chris Crocker-White <chriscw@balena.io>
=> Add NanoPi Neo Air as supported device

README.md, balena.yml, pihole/Dockerfile, unbound/unbound.conf
Document how to enable Unbound recursive DNS for advanced users.
=> Change to Cloudflare upstream DNS by default 

unbound/Dockerfile
Upgrade Unbound to 1.13.1 from `klutchell/unbound-dnscrypt:1.13.1`
=> Upgrade Unbound to 1.13.1

README.md
doc updates for Unbound and D-Bus per #73
=> doc updates for Unbound and D-Bus

pihole/cont-init.d/10-custom.sh
Related-to: https://github.com/klutchell/balena-pihole/issues/82
=> Skip hostname setup if BALENA_HOSTNAME is empty

balena.yml
Signed-off-by: Flynn Joffray <flynn@balena.io>
=> Adding `version` to balena.yml

README.md, balena.yml, docker-compose.yml, pihole/Dockerfile, pihole/cont-init.d/10-custom.sh
The tag format has changed, see these release notes:
https://github.com/pi-hole/docker-pi-hole/releases/tag/2021.09
Resolves: https://github.com/klutchell/balena-pihole/issues/90
=> Update Pi-hole to 2021.09

balena.yml
=> Use proper semver without leading zeroes

.github/dependabot.yml, .github/workflows/balena.yml, balena.yml, pihole/Dockerfile
https://github.com/pi-hole/docker-pi-hole/releases/tag/2021.11
=> Update Pi-hole to release 2011.11

balena.yml
=> Use proper semver without leading zero.

pihole/Dockerfile
https://github.com/pi-hole/PADD/releases/tag/v3.6.7
Signed-off by: Roddie Hasan <roddie@krweb.net>
=> Upgrade PADD to 3.6.7

balena.yml, docker-compose.yml, pihole/Dockerfile
https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.04
https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.04.1
=> Upgrade Pihole to 2022.04.1

postUpgrade.sh, renovate.json
=> Apply renovate postUpgradeTasks to bump balena.yml

.github/workflows/renovate.yml, renovate.json
See: https://github.com/renovatebot/github-action
=> Configure renovate github-action

.github/dependabot.yml
=> Disable dependabot in favour of renovate

README.md, docker-compose.yml, pihole/Dockerfile
Fixes: https://github.com/klutchell/balena-pihole/issues/145
=> Restore console-setup functionality without privileged mode

balena.yml, pihole/Dockerfile, pihole/cont-init.d/10-custom.sh, pihole/services/padd/finish, pihole/services/padd/run
Resolves: https://github.com/klutchell/balena-pihole/issues/166
=> Update pihole/pihole Docker tag to v2022.08

pihole/Dockerfile
https://github.com/pi-hole/PADD/releases/tag/v3.8.0
=> Update PADD to v3.8.0

.github/renovate.json, pihole/Dockerfile
=> Use renovate to bump PADD releases

pihole/Dockerfile, pihole/services/padd/run
Resolves: https://github.com/klutchell/balena-pihole/issues/187
=> Pre-calculate screen size for PADD

.github/workflows/balena.yml
=> Push to both fleet and app

README.md, docker-compose.yml, tailscale/Dockerfile.template
Depends-on: https://github.com/klutchell/balena-pihole/pull/207
=> Add optional tailscale service

docker-compose.yml, hostname/Dockerfile.template
=> Update hostname and fbcp blocks to latest

README.md
Small PR - adjusts the correct location of the `unbound.conf` and `a-records.conf` files in `README.md`.
=> Update `unbound.conf` and `a-records.conf` references
