klutchell/balena-pihole

- README.md
- docker-compose.yml
- pihole/Dockerfile
- pihole/services/fbcp/finish
- pihole/services/fbcp/run
- pihole/services/padd/finish
- pihole/services/padd/run
Expanded the Pi-hole container to include fbcp and PADD for use with a Pi-TFT screen. Added additional information to README.
> Expanded Pi-hole container and README

- pihole/Dockerfile
bc was removed as a Pi-hole dependency in the latest version but is required by PADD.
> Install bc (required by PADD)

- README.md
- pihole/Dockerfile
- pihole/init/30-checktft.sh
Disabled fbcp and PADD services by default, check on startup to see if /dev/fb1 exists, if it does enable the services otherwise leave them disabled. Updated README to include note about WiFi interface.
> Added checking if TFT framebuffer present before starting fbcp

- pihole/Dockerfile
I did further testing and found that although FBCP compiles with Stretch the binary doesn't work within the Pi-hole image. Changed to compiling it on Jessie and everything works as it should.
Signed-off-by: Chris Crocker-White <chriscw@balena.io>
> Use Jessie for compiling FBCP otherwise it doesn't produce output

- pihole/Dockerfile.aarch64
> Add aarch64 file to enable 32-bit build for Pi 4

- README.md
Added query string params to the deploy button as some platforms strip the referrer details causing the deploy button to fail to work.
Signed-off-by: Aaron Shaw <shawaj@gmail.com>
> docs: add query string params to deploy button

- README.md
- balena.yml
- docker-compose.yml
Added `PIHOLE_DNS_` to docs and YAML files to replace deprecated `DNS1`/`DNS2` syntax.
> Update environment variables and docs

- README.md
- dbus/Dockerfile
- dbus/init.sh
- docker-compose.yml
Note that `dtoverlay` is a new label and `FBCP_DISPLAY` option that relies on `BALENA_HOST_CONFIG_dtoverlay` being set in order to use the legacy rpi-fbcp driver (supports more displays via kernel device trees).
balenablocks PR is here: https://github.com/balenablocks/fbcp/pull/5
Change-type: minor
Connects-to: https://github.com/klutchell/balena-pihole/issues/64
> fbcp: use balenablocks/fbcp:1.0.0 with dtoverlay support

- unbound/unbound.conf
Plex requires DNS rebinding in order to provide secure connectivity to some devices on a LAN.  Unbound DNS Binding Protection breaks this.  Adding `plex.direct` as a private domain to work around this.
> Add Plex as private-domain to allow DNS rebinding

- pihole/Dockerfile
Upgrade to v5.8.1 - https://github.com/pi-hole/docker-pi-hole/releases/tag/v5.8.1
Hold until April 28.
> Upgrade to Pi-hole v5.8 and FTL v5.8.1

- balena.yml
Pushing a new release to an existing fleet will automatically increment the `-rev` suffix.
> Set the fleet semver to the Pi-hole version

- .github/workflows/balena.yml
- balena.yml
- pihole/Dockerfile
https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.01.1
> Update Pi-hole to release 2022.01.1

- .github/workflows/balena.yml
Expect it to fail for external users and forks.
> Allow any user to run the balena deploy action

- balena.yml
- pihole/Dockerfile
https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.02
https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.02.1
> Update Pi-hole to release 2022.02.1

- docker-compose.yml
Resolves: https://github.com/klutchell/balena-pihole/issues/131
> Create a tmpfs mount for logs to avoid storage wear

- README.md
- balena.yml
Changed "static IP" to "static IP reservation" to clarify the instruction re #204.
> Clarify wording about DHCP reservations

- README.md
- balena.yml
- pihole/Dockerfile
- pihole/cont-init.d/10-custom.sh
Exclude resin-dns from port bindings to avoid conflicts.
> Bind to all interfaces by default

- docker-compose.yml
- pihole/Dockerfile
This is especially useful to access the dashboard over tailnet.
Resolves: https://github.com/klutchell/balena-pihole/issues/208
> Bind web dashboard to all interfaces by default

- README.md
- docker-compose.yml
- tailscale/Dockerfile.template
The balena wrapper wasn't adding any useful functionality and was slower to get updates.
> Use official tailscale docker image

- docker-compose.yml
This is to align with the official docs for v6.
> Update the default capabilities of the Pi-hole service

- padd/Dockerfile
See: https://github.com/pi-hole/PADD/releases/tag/v4.0.0
> Pin to PADD v4.0.0 and allow renovate to manage tags

- docker-compose.yml
- pihole/Dockerfile
- pihole/balena-init.sh
As of pihole v6 we are no longer persisting
dnsmasq	 config volumes, so we can set these persistent config settings at build time.
> Move some dnsmasq config to build time
